{{- if and .Values.awspoller.enabled .Values.awspoller.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-poller
  labels:
    app: ssd
    component: aws-poller
{{ include "ssd.standard-labels" . | indent 4 }}
{{- with .Values.awspoller.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
