imageCredentials:
  repoUrl: docker.io
  # Update this is using a private repo such as ACR, ECR, GCR, JFrog, etc.
  registry: opsmx11
aibom:
  image:
    tag: "2026-08-00-rc3"

aishield:
  image:
    tag: "2026-08-00-rc3"

artifactscan:
  image:
    tag: "2026-08-00-rc3"

airemediation:
  image:
    tag: "2026-08-00-rc3"

cbom:
  image:
    tag: "2.1.12"

checkmarx:
  image:
    tag: "2026-08-00-rc3"

dlvs:
  image:
    tag: "b5b8de1-4"

hbom:
  image:
    tag: "2026-08-00-rc3"

kubescape:
  image:
    tag: "2026-08-00-rc3"

licensegenerator:
  image:
    tag: "2026-08-00-rc3"

mobsf:
  image:
    tag: "v4.1.3"

opsmxassistant:
  image:
    tag: "2026-08-00-rc3"

projectmonitor:
  image:
    tag: "2026-08-00-rc3"

prismiac:
  image:
    tag: "2026-08-00-rc3"

pentestgpt:
  image:
    tag: "2026-08-00-rc3"

shieldgateway:
  image:
    tag: "2026-08-00-rc3"

shieldprocessor:
  image:
    tag: "2026-08-00-rc3"

snykmonitor:
  image:
    tag: "2026-08-00-rc3"

sourcescan:
  image:
    tag: "2026-08-00-rc3"

supplychainapi:
  image:
    tag: "2026-08-00-rc4"

supplychainpreprocessor:
  image:
    tag: "2026-08-00-rc3"

ssdauditservice:
  image:
    tag: "2026-08-00-rc3"

ssdgate:
  image:
    repository: ssd-gate
    tag: "2026-08-00-rc3"

ssdnotificationservice:
  image:
    tag: "2026-08-00-rc3"

ssdopa:
  image:
    tag: "2026-08-00-rc3"

ssdrescheduler:
  image:
    tag: "2026-08-00-rc3"

tokenmachine:
  image:
    tag: "6a6e427-77"

toolchain:
  image:
    tag: "2026-08-00-rc3"

ui:
  image:
    tag: "2026-08-00-rc3"
  serviceAnnotations:
    awsAnnotationsGo: HERE

awspoller:
  image:
    tag: "2026-08-00-rc4"

kubernetes-detector:
  image:
    tag: "2026-08-00-rc3"

mcpserver:
  image:
    tag: "2026-08-00-rc3"

zap:
  image:
    repository: zap
    tag: "2026-03-00"
