{{- $a := .Values.aiSecrets.aig }}
{{- if and $a.create (not $a.existingSecret) (ne $a.tenantApiKey "REPLACE_ME") }}
apiVersion: v1
kind: Secret
metadata:
  name: aig-api-key
  namespace: {{ .Release.Namespace }}
  labels:
    app: ssd
    component: supplychain-api
{{ include "ssd.standard-labels" . | indent 4 }}
type: Opaque
stringData:
  TenantApiKey: {{ $a.tenantApiKey | quote }}
{{- end }}
